name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Docker images
      uses: actions/cache@v2
      with:
        path: /var/lib/docker/image
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag osdev

    - name: Clean all
      run: docker run osdev make clean-all

    - name: Make the binaries and the ISO image
      run: docker run osdev make iso
