name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: rustembedded/osdev-utils:2021.12

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Docker images
      uses: actions/cache@v2
      with:
        path: /var/lib/docker/image
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-

    - name: Clean all
      run: make clean-all
      
    - name: Compile binary
      run: make bin
